/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.dg.admindashboard;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author TASNUVA
 */
public class AdminMenubar extends javax.swing.JPanel {

    private JButton selectedButton = null;

    /**
     * Creates new form AdminMenubar
     */
    public AdminMenubar() {
        initComponents();
        //setOpaque(false);
        //btnProfile.addActionListener(e -> setSelectedButton(btnProfile));
        //btnSearch.addActionListener(e -> setSelectedButton(btnSearch));
        //btnView.addActionListener(e -> setSelectedButton(btnView));
        //btnAssignment.addActionListener(e -> setSelectedButton(btnAssignment));
        //btnViewAlerts.addActionListener(e -> setSelectedButton(btnViewAlerts));
        //btnLogout.addActionListener(e -> setSelectedButton(btnLogout));
    }

    public void setSelectedButton(JButton button) {
        selectedButton = button;
        repaint();
    }

    public javax.swing.JButton getBtnViewVolunteer() {
        return btnView;
    }

    public javax.swing.JButton getBtnViewAlerts() {
        return btnViewAlerts;
    }

    public javax.swing.JButton getBtnAssignment() {
        return btnAssignment;
    }

    public javax.swing.JButton getBtnSearch() {
        return btnSearch;
    }

    public javax.swing.JButton getBtnLogout() {
        return btnLogout;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSearch = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnAssignment = new javax.swing.JButton();
        btnViewAlerts = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(215, 525));

        btnSearch.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/SearchVolunteericon.png"))); // NOI18N
        btnSearch.setText("Search Volunteer");
        btnSearch.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnSearch.setContentAreaFilled(false);
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSearch.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        btnView.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnView.setForeground(new java.awt.Color(255, 255, 255));
        btnView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/viewvolunteer.png"))); // NOI18N
        btnView.setText("View Volunteer");
        btnView.setBorder(null);
        btnView.setContentAreaFilled(false);
        btnView.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnView.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnView.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btnAssignment.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnAssignment.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/dg/admindashboardlogo/ViewAssignment_1.png"))); // NOI18N
        btnAssignment.setText("Assignment");
        btnAssignment.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnAssignment.setContentAreaFilled(false);
        btnAssignment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAssignment.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAssignment.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAssignment.addActionListener(this::btnAssignmentActionPerformed);

        btnViewAlerts.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnViewAlerts.setForeground(new java.awt.Color(255, 255, 255));
        btnViewAlerts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/dg/admindashboardlogo/viewalerts.png"))); // NOI18N
        btnViewAlerts.setText("View Alerts");
        btnViewAlerts.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnViewAlerts.setContentAreaFilled(false);
        btnViewAlerts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewAlerts.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnViewAlerts.addActionListener(this::btnViewAlertsActionPerformed);

        btnLogout.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/logout.png"))); // NOI18N
        btnLogout.setText("Log Out");
        btnLogout.setBorder(null);
        btnLogout.setContentAreaFilled(false);
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnLogout.setIconTextGap(3);
        btnLogout.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        btnProfile.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/myprofile.png"))); // NOI18N
        btnProfile.setText("My Profile");
        btnProfile.setBorder(null);
        btnProfile.setContentAreaFilled(false);
        btnProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProfile.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProfile.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnProfile.addActionListener(this::btnProfileActionPerformed);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/dg/admindashboardlogo/adminlogofinal.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnProfile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAssignment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewAlerts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAssignment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewAlerts, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewAlertsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAlertsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewAlertsActionPerformed

    private void btnAssignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAssignmentActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    @Override
    protected void paintChildren(Graphics grphcs) {

        Graphics2D g2 = (Graphics2D) grphcs;

        g2.setRenderingHint(
                RenderingHints.KEY_ANTIALIASING,
                RenderingHints.VALUE_ANTIALIAS_ON
        );

        GradientPaint g = new GradientPaint(
                0, 0,
                Color.decode("#AA076B"),
                0, getHeight(),
                Color.decode("#61045F")
        );

        g2.setPaint(g);

        g2.fillRoundRect(
                0,
                0,
                getWidth(),
                getHeight(),
                15,
                15
        );

        g2.fillRect(
                getWidth() - 20,
                0,
                getWidth(),
                getHeight()
        );
        
        // LEFT SIDE INDICATOR
        if (selectedButton != null) {

            g2.setColor(Color.WHITE);

            int y = selectedButton.getY();
            int height = selectedButton.getHeight();

            g2.fillRoundRect(
                    0,
                    y,
                    6,
                    height,
                    6,
                    6
            );
        }

        super.paintChildren(grphcs);
    }

    public JButton getBtnProfile() {
        return btnProfile;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignment;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnView;
    private javax.swing.JButton btnViewAlerts;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
