/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.dg.volunteerform;

public class MainVolunteerPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainVolunteerPanel
     */
    public MainVolunteerPanel() {
        initComponents();
        setSize(900, 600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        specializedSkillsPanel1 = new com.dg.volunteerform.SpecializedSkillsPanel();
        physicalCapabilitiesExperiencePanel1 = new com.dg.volunteerform.PhysicalCapabilitiesExperiencePanel();
        addressPanel1 = new com.dg.volunteerform.AddressPanel();
        personalInfoPanel1 = new com.dg.volunteerform.PersonalInfoPanel();

        setLayout(new java.awt.CardLayout());
        add(specializedSkillsPanel1, "SKILLS");
        add(physicalCapabilitiesExperiencePanel1, "EXPERIENCE");
        add(addressPanel1, "ADDRESS");
        add(personalInfoPanel1, "PERSONAL");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.dg.volunteerform.AddressPanel addressPanel1;
    private com.dg.volunteerform.PersonalInfoPanel personalInfoPanel1;
    private com.dg.volunteerform.PhysicalCapabilitiesExperiencePanel physicalCapabilitiesExperiencePanel1;
    private com.dg.volunteerform.SpecializedSkillsPanel specializedSkillsPanel1;
    // End of variables declaration//GEN-END:variables
}
