/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.dg.volunteerform;

import com.dg.dbconnection.VolunteerData;
import com.dg.homepage.Homepage1;
import java.awt.*;
import javax.swing.*;
import java.time.LocalDate;
import java.time.Period;
import javax.swing.border.Border;
import java.awt.Color;
public class PersonalInfoPanel extends javax.swing.JPanel {

    /**
     * Creates new form PersonalInfoPanel
     */
    private Border defaultTextFieldBorder;
private Border defaultComboBoxBorder;
    private ButtonGroup genderGroup;

    public PersonalInfoPanel() {
        initComponents();
        setBackground(Color.WHITE);
        setOpaque(false);
        // store default borders
    defaultTextFieldBorder = txtVolunteerName.getBorder();
    defaultComboBoxBorder = VolunteerBirthDate.getBorder();

        genderGroup = new ButtonGroup();
        genderGroup.add(VolunteerGenderMale);
        genderGroup.add(VolunteerGenderFemale);
        genderGroup.add(VolunteerGenderOther);

    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        Graphics2D g2 = (Graphics2D) g.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        int arc = 25;
        int shadow = 8;

        // Shadow
        g2.setColor(new Color(0, 0, 0, 60));
        g2.fillRoundRect(shadow, shadow,
                getWidth() - shadow,
                getHeight() - shadow,
                arc, arc);

        // Background
        g2.setColor(getBackground());
        g2.fillRoundRect(0, 0,
                getWidth() - shadow,
                getHeight() - shadow,
                arc, arc);

        g2.dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VolunteerName = new javax.swing.JLabel();
        txtVolunteerName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        VolunteerBirthDate = new javax.swing.JComboBox<>();
        VolunteerBirthMonth = new javax.swing.JComboBox<>();
        VolunteerBirthYear = new javax.swing.JComboBox<>();
        lbVolunteerGender = new javax.swing.JLabel();
        VolunteerGenderMale = new javax.swing.JRadioButton();
        VolunteerGenderFemale = new javax.swing.JRadioButton();
        VolunteerGenderOther = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txtVolunteerNationalID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtVolunteerPhoneNumber = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtVolunteerEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtVolunteerEmergencyContactNo = new javax.swing.JTextField();
        PersonalInfoNextButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        PersonalInfoBackButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        VolunteerName.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        VolunteerName.setText("Name");

        txtVolunteerName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setText("Birth Date");

        VolunteerBirthDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Select Date---", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        VolunteerBirthDate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));
        VolunteerBirthDate.addActionListener(this::VolunteerBirthDateActionPerformed);

        VolunteerBirthMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Select Month---", "January", "February", "March", "April", "May ", "June", "July ", "August", "September", "October", "November", "December", " " }));
        VolunteerBirthMonth.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));
        VolunteerBirthMonth.addActionListener(this::VolunteerBirthMonthActionPerformed);

        VolunteerBirthYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Select Year---", "2025", "2024", "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940", "1939", "1938", "1937", "1936", "1935", "1934", "1933", "1932", "1931", "1930", "1929", "1928", "1927", "1926", "1925", "1924", "1923", "1922", "1921", "1920", "1919", "1918", "1917", "1916", "1915", "1914", "1913", "1912", "1911", "1910", "1909", "1908", "1907", "1906", "1905", "1904", "1903", "1902", "1901", "1900" }));
        VolunteerBirthYear.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));
        VolunteerBirthYear.addActionListener(this::VolunteerBirthYearActionPerformed);

        lbVolunteerGender.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lbVolunteerGender.setText("Gender");

        VolunteerGenderMale.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        VolunteerGenderMale.setText("Male");

        VolunteerGenderFemale.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        VolunteerGenderFemale.setText("Female");
        VolunteerGenderFemale.addActionListener(this::VolunteerGenderFemaleActionPerformed);

        VolunteerGenderOther.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        VolunteerGenderOther.setText("Other");
        VolunteerGenderOther.addActionListener(this::VolunteerGenderOtherActionPerformed);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setText("National ID");

        txtVolunteerNationalID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));
        txtVolunteerNationalID.addActionListener(this::txtVolunteerNationalIDActionPerformed);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        jLabel4.setText("Contact Details");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel5.setText("Phone Number");

        txtVolunteerPhoneNumber.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));
        txtVolunteerPhoneNumber.addActionListener(this::txtVolunteerPhoneNumberActionPerformed);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel6.setText("Email");

        txtVolunteerEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));
        txtVolunteerEmail.addActionListener(this::txtVolunteerEmailActionPerformed);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel7.setText("Blood Group");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Select Blood Group---", "A+", "A-", "AB+", "AB-", "B+", "B-", "O+", "O-" }));
        jComboBox4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));
        jComboBox4.addActionListener(this::jComboBox4ActionPerformed);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel8.setText("Emergency Contact ");

        txtVolunteerEmergencyContactNo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));

        PersonalInfoNextButton1.setBackground(new java.awt.Color(0, 153, 153));
        PersonalInfoNextButton1.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        PersonalInfoNextButton1.setForeground(new java.awt.Color(204, 255, 255));
        PersonalInfoNextButton1.setText("Next");
        PersonalInfoNextButton1.setAutoscrolls(true);
        PersonalInfoNextButton1.addActionListener(this::PersonalInfoNextButton1ActionPerformed);

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Personal Details");

        PersonalInfoBackButton.setBackground(new java.awt.Color(0, 153, 153));
        PersonalInfoBackButton.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        PersonalInfoBackButton.setForeground(new java.awt.Color(204, 255, 255));
        PersonalInfoBackButton.setText("Back");
        PersonalInfoBackButton.addActionListener(this::PersonalInfoBackButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtVolunteerEmergencyContactNo)
                                    .addComponent(jComboBox4, 0, 242, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3)
                                    .addComponent(lbVolunteerGender)
                                    .addComponent(jLabel1)
                                    .addComponent(VolunteerName))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(50, 50, 50)
                                            .addComponent(VolunteerBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(50, 50, 50)
                                            .addComponent(VolunteerBirthMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                            .addComponent(VolunteerBirthYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(51, 51, 51)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtVolunteerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtVolunteerPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtVolunteerName, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtVolunteerNationalID, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(VolunteerGenderMale)
                                                .addGap(45, 45, 45)
                                                .addComponent(VolunteerGenderFemale)
                                                .addGap(45, 45, 45)
                                                .addComponent(VolunteerGenderOther)))))))
                        .addGap(0, 95, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PersonalInfoBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PersonalInfoNextButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VolunteerName)
                    .addComponent(txtVolunteerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(VolunteerBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VolunteerBirthMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VolunteerBirthYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbVolunteerGender)
                    .addComponent(VolunteerGenderMale)
                    .addComponent(VolunteerGenderFemale)
                    .addComponent(VolunteerGenderOther))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtVolunteerNationalID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtVolunteerPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtVolunteerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtVolunteerEmergencyContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PersonalInfoNextButton1)
                    .addComponent(PersonalInfoBackButton))
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void VolunteerBirthDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolunteerBirthDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VolunteerBirthDateActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void txtVolunteerNationalIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVolunteerNationalIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVolunteerNationalIDActionPerformed

    private void PersonalInfoNextButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonalInfoNextButton1ActionPerformed

        // Name validation
        
        if (txtVolunteerName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Name required!");
            txtVolunteerName.requestFocusInWindow();
            txtVolunteerName.setBorder(
                    BorderFactory.createMatteBorder(0,0,2,0,Color.RED)
            );
            return;
        }
        else
        {
            txtVolunteerName.setBorder(defaultTextFieldBorder);
        }
        // Birthdate + Age Validation 

// Check selection
        if (VolunteerBirthDate.getSelectedIndex() == 0) {

            JOptionPane.showMessageDialog(this, "Please select birth date!");
            VolunteerBirthDate.requestFocusInWindow();
            VolunteerBirthDate.setBorder(
                    BorderFactory.createMatteBorder(0,0,2,0,Color.RED)
            );
            return;
        }
        else
        {
            VolunteerBirthDate.setBorder(defaultComboBoxBorder);
        }
        if ( VolunteerBirthMonth.getSelectedIndex() == 0) {

            JOptionPane.showMessageDialog(this, "Please select birth month!");
            VolunteerBirthMonth.requestFocusInWindow();
            VolunteerBirthMonth.setBorder(
                    BorderFactory.createMatteBorder(0,0,2,0,Color.RED)
            );
            return;
        }
        else
        {
            VolunteerBirthMonth.setBorder(defaultComboBoxBorder);
        }
        if ( VolunteerBirthYear.getSelectedIndex() == 0) {

            JOptionPane.showMessageDialog(this, "Please select birth year!");
            VolunteerBirthYear.requestFocusInWindow();
            VolunteerBirthYear.setBorder(
                    BorderFactory.createMatteBorder(0,0,2,0,Color.RED)
            );
            return;
        }
        else
        {
            VolunteerBirthYear.setBorder(defaultComboBoxBorder);
        }

        try {
            int day = Integer.parseInt(VolunteerBirthDate.getSelectedItem().toString());
            int year = Integer.parseInt(VolunteerBirthYear.getSelectedItem().toString());

            String monthStr = VolunteerBirthMonth.getSelectedItem().toString();
            int month;

            switch (monthStr) {
                case "January" ->
                    month = 1;
                case "February" ->
                    month = 2;
                case "March" ->
                    month = 3;
                case "April" ->
                    month = 4;
                case "May" ->
                    month = 5;
                case "June" ->
                    month = 6;
                case "July" ->
                    month = 7;
                case "August" ->
                    month = 8;
                case "September" ->
                    month = 9;
                case "October" ->
                    month = 10;
                case "November" ->
                    month = 11;
                case "December" ->
                    month = 12;
                default ->
                    throw new Exception();
            }

            // Month-wise day validation 
            boolean leapYear
                    = (year % 4 == 0 && year % 100 != 0) || (year % 400 == 0);

            if (month == 2) { // February
                if (leapYear && day > 29) {
                    JOptionPane.showMessageDialog(this,
                            "February in leap year has maximum 29 days!");
                    VolunteerBirthDate.requestFocusInWindow();
                     VolunteerBirthDate.setBorder(
                    BorderFactory.createMatteBorder(0,0,2,0,Color.RED)
            );
                    return;
                }
                if (!leapYear && day > 28) {
                    JOptionPane.showMessageDialog(this,
                            "February has maximum 28 days!");
                    VolunteerBirthDate.requestFocusInWindow();
                     VolunteerBirthDate.setBorder(
                    BorderFactory.createMatteBorder(0,0,2,0,Color.RED)
            );
                    return;
                }
            }

            // Months with 30 days
            if ((month == 4 || month == 6 || month == 9 || month == 11) && day > 30) {
                JOptionPane.showMessageDialog(this,
                        "Selected month has maximum 30 days!");
                VolunteerBirthDate.requestFocusInWindow();
                 VolunteerBirthDate.setBorder(
                    BorderFactory.createMatteBorder(0,0,2,0,Color.RED)
            );
                return;
            }

            // Proper date creation 
            LocalDate birthDate = LocalDate.of(year, month, day);
            LocalDate today = LocalDate.now();

            // Future date check
            if (birthDate.isAfter(today)) {
                JOptionPane.showMessageDialog(this,
                        "Birth date cannot be in future!");
                VolunteerBirthDate.requestFocusInWindow();
                 VolunteerBirthDate.setBorder(
                    BorderFactory.createMatteBorder(0,0,2,0,Color.RED)
            );
                return;
            }

            // Age calculation
            int age = Period.between(birthDate, today).getYears();

            if (age < 18) {
                JOptionPane.showMessageDialog(this,
                        "Minimum age must be 18 years!\nYour age: " + age);
                VolunteerBirthDate.requestFocusInWindow();
                 VolunteerBirthDate.setBorder(
                    BorderFactory.createMatteBorder(0,0,2,0,Color.RED)
            );
                return;
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Invalid birth date!");
            VolunteerBirthDate.requestFocusInWindow();
             VolunteerBirthDate.setBorder(
                    BorderFactory.createMatteBorder(0,0,2,0,Color.RED)
            );
            return;
        }

        if (!VolunteerGenderMale.isSelected() && !VolunteerGenderFemale.isSelected() && !VolunteerGenderOther.isSelected()) {
            JOptionPane.showMessageDialog(this, "Please select your gender!");
            lbVolunteerGender.setForeground(Color.RED);
            return;
        }

        // National ID Full Validation
        {
            String nid = txtVolunteerNationalID.getText().trim();

            try {
                // Reset border first (success case)
                txtVolunteerNationalID.setBorder(
                        UIManager.getBorder("TextField.border")
                );

                // Empty check
                if (nid.isEmpty()) {
                    throw new ValidationException("National ID is required!");
                }

                // Numeric only check
                if (!nid.matches("\\d+")) {
                    throw new ValidationException("National ID must contain digits only!");
                }

                // Length validation (Bangladesh NID)
                if (!(nid.length() == 10 || nid.length() == 13 || nid.length() == 17)) {
                    throw new ValidationException("Valid National ID required!");
                }

                // Age check (NID holder must be 18+)
                LocalDate today = LocalDate.now();
                int day = Integer.parseInt(VolunteerBirthDate.getSelectedItem().toString());
                int year = Integer.parseInt(VolunteerBirthYear.getSelectedItem().toString());

                String monthStr = VolunteerBirthMonth.getSelectedItem().toString();
                int month;

                month = switch (monthStr) {
                    case "January" ->
                        1;
                    case "February" ->
                        2;
                    case "March" ->
                        3;
                    case "April" ->
                        4;
                    case "May" ->
                        5;
                    case "June" ->
                        6;
                    case "July" ->
                        7;
                    case "August" ->
                        8;
                    case "September" ->
                        9;
                    case "October" ->
                        10;
                    case "November" ->
                        11;
                    case "December" ->
                        12;
                    default ->
                        1;
                };
                LocalDate birthDate = LocalDate.of(year, month, day);

                int age = Period.between(birthDate, today).getYears();

                if (age < 18) {
                    throw new ValidationException(
                            "National ID is only valid for age 18+\nYour age: " + age
                    );
                }

            } catch (ValidationException e) {
                // Show message
                JOptionPane.showMessageDialog(this, e.getMessage());

                // Red border on error
                txtVolunteerNationalID.setBorder(
                        BorderFactory.createMatteBorder(0,0,2,0,Color.RED)
                );

                // Grab focus
                txtVolunteerNationalID.requestFocusInWindow();
                txtVolunteerNationalID.setBorder(
                    BorderFactory.createMatteBorder(0,0,2,0,Color.RED)
            );
                
                return;
            }
        }
        // End National ID Validation

        // Volunteer Phone Number
        String phone = txtVolunteerPhoneNumber.getText().trim();
        if (phone.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Phone number required!");
            txtVolunteerPhoneNumber.requestFocusInWindow();
            txtVolunteerPhoneNumber.setBorder(BorderFactory.createMatteBorder(0,0,2,0,Color.RED));
            return;
        } else if (!phone.matches("01[3-9]\\d{8}")) {
            JOptionPane.showMessageDialog(this, "Invalid phone number!\nExample: 017XXXXXXXX");
            txtVolunteerPhoneNumber.requestFocusInWindow();
            txtVolunteerPhoneNumber.setBorder(BorderFactory.createMatteBorder(0,0,2,0,Color.RED));
            return;
        } else {
            txtVolunteerPhoneNumber.setBorder(UIManager.getBorder("TextField.border")); // Reset border if valid
        }

// Email
        String email = txtVolunteerEmail.getText().trim();
        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email required!");
            txtVolunteerEmail.requestFocusInWindow();
            txtVolunteerEmail.setBorder(BorderFactory.createMatteBorder(0,0,2,0,Color.RED));
            return;
        } else if (!email.matches("^[\\w.-]+@[\\w.-]+\\.[A-Za-z]{2,}$")) {
            JOptionPane.showMessageDialog(this, "Enter a valid email address!");
            txtVolunteerEmail.requestFocusInWindow();
            txtVolunteerEmail.setBorder(BorderFactory.createMatteBorder(0,0,2,0,Color.RED));
            return;
        } else {
            txtVolunteerEmail.setBorder(UIManager.getBorder("TextField.border"));
        }

        //Blood Group Select
        if (jComboBox4.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Please select a blood group!");
            jComboBox4.requestFocusInWindow();
            jComboBox4.setBorder(BorderFactory.createMatteBorder(0,0,2,0,Color.RED));
            return;
        }

// Emergency Contact Number
        String ephone = txtVolunteerEmergencyContactNo.getText().trim();
        if (ephone.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Emergency contact number required!");
            txtVolunteerEmergencyContactNo.requestFocusInWindow();
            txtVolunteerEmergencyContactNo.setBorder(BorderFactory.createMatteBorder(0,0,2,0,Color.RED));
            return;
        } else if (!ephone.matches("01[3-9]\\d{8}")) {
            JOptionPane.showMessageDialog(this, "Invalid emergency contact number!");
            txtVolunteerEmergencyContactNo.requestFocusInWindow();
            txtVolunteerEmergencyContactNo.setBorder(BorderFactory.createMatteBorder(0,0,2,0,Color.RED));
            return;
        } else {
            txtVolunteerEmergencyContactNo.setBorder(UIManager.getBorder("TextField.border"));
        }

        

        if (VolunteerGenderMale.isSelected()) {
        } else if (VolunteerGenderFemale.isSelected()) {
        } else if (VolunteerGenderOther.isSelected()) {
        }
        


        // If everything is OK
        MainVolunteerFrame frame = (MainVolunteerFrame) SwingUtilities.getWindowAncestor(this);
        VolunteerData volunteer=frame.getVolunteerData();
        volunteer.setFullName(txtVolunteerName.getText().trim());
volunteer.setBirthDate(Integer.parseInt(VolunteerBirthDate.getSelectedItem().toString()));
volunteer.setBirthMonth(VolunteerBirthMonth.getSelectedItem().toString());
volunteer.setBirthYear(Integer.parseInt(VolunteerBirthYear.getSelectedItem().toString()));
volunteer.setGender(
        VolunteerGenderMale.isSelected() ? "Male" :
        VolunteerGenderFemale.isSelected() ? "Female" : "Other"
);
volunteer.setNid(txtVolunteerNationalID.getText().trim());

// 3️⃣ Set contact info
volunteer.setPhoneNumber(txtVolunteerPhoneNumber.getText().trim());
volunteer.setEmail(txtVolunteerEmail.getText().trim());
volunteer.setBloodGroup(jComboBox4.getSelectedItem().toString());
volunteer.setEmergencyContactNumber(txtVolunteerEmergencyContactNo.getText().trim());

        frame.showCard("ADDRESS");
    }//GEN-LAST:event_PersonalInfoNextButton1ActionPerformed

    private void VolunteerBirthYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolunteerBirthYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VolunteerBirthYearActionPerformed

    private void VolunteerGenderFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolunteerGenderFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VolunteerGenderFemaleActionPerformed

    private void VolunteerGenderOtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolunteerGenderOtherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VolunteerGenderOtherActionPerformed

    private void VolunteerBirthMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolunteerBirthMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VolunteerBirthMonthActionPerformed

    private void txtVolunteerPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVolunteerPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVolunteerPhoneNumberActionPerformed

    private void txtVolunteerEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVolunteerEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVolunteerEmailActionPerformed

    private void PersonalInfoBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonalInfoBackButtonActionPerformed
        // TODO add your handling code here:
        JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);

        // Homepage frame
        Homepage1 homepage = new Homepage1();
        homepage.setVisible(true);

        // Current frame close
        currentFrame.dispose();
    }//GEN-LAST:event_PersonalInfoBackButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PersonalInfoBackButton;
    private javax.swing.JButton PersonalInfoNextButton1;
    private javax.swing.JComboBox<String> VolunteerBirthDate;
    private javax.swing.JComboBox<String> VolunteerBirthMonth;
    private javax.swing.JComboBox<String> VolunteerBirthYear;
    private javax.swing.JRadioButton VolunteerGenderFemale;
    private javax.swing.JRadioButton VolunteerGenderMale;
    private javax.swing.JRadioButton VolunteerGenderOther;
    private javax.swing.JLabel VolunteerName;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbVolunteerGender;
    private javax.swing.JTextField txtVolunteerEmail;
    private javax.swing.JTextField txtVolunteerEmergencyContactNo;
    private javax.swing.JTextField txtVolunteerName;
    private javax.swing.JTextField txtVolunteerNationalID;
    private javax.swing.JTextField txtVolunteerPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
