/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.dg.volunteerdashboard;

import javax.swing.JButton;

/**
 *
 * @author USER
 */
public class VolunteerMenu extends javax.swing.JPanel {

    /**
     * Creates new form VolunteerMenu
     */
    public VolunteerMenu() {
        initComponents();

        //setOpaque(false);
        //setBackground(new java.awt.Color(0, 0, 0, 0));
        styleButtons();
        setOpaque(false);
        setBackground(new java.awt.Color(0, 0, 0, 0));
    }

    private void styleButtons() {
        JButton[] buttons = {
            //BtnProfile, BtnSuperAdmin,
            //BtnAdmin, 
            BtnAlert, BtnWork, BtnLogOut
        };

        for (JButton btn : buttons) {
            btn.setBorderPainted(false);
            btn.setFocusPainted(false);
            btn.setContentAreaFilled(false);
            btn.setOpaque(false);
        }
    }

    public JButton getBtnProfile() {
        return BtnProfile;
    }

    public JButton getBtnAlert() {
        return BtnAlert;
    }

    public JButton getBtnWork() {
        return BtnWork;
    }

    public JButton getBtnLogout() {
        return BtnLogOut;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogoVolunteer = new javax.swing.JLabel();
        BtnProfile = new javax.swing.JButton();
        BtnAlert = new javax.swing.JButton();
        BtnWork = new javax.swing.JButton();
        BtnLogOut = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(227, 688));
        setMinimumSize(new java.awt.Dimension(227, 688));
        setPreferredSize(new java.awt.Dimension(227, 688));

        LogoVolunteer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoVolunteer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/Volunteer_Logo_Styled4.png"))); // NOI18N
        LogoVolunteer.setAutoscrolls(true);

        BtnProfile.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        BtnProfile.setForeground(new java.awt.Color(255, 255, 255));
        BtnProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/myprofile.png"))); // NOI18N
        BtnProfile.setText("My Profile");
        BtnProfile.setAutoscrolls(true);
        BtnProfile.setBorder(null);
        BtnProfile.setContentAreaFilled(false);
        BtnProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnProfile.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnProfile.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnProfile.addActionListener(this::BtnProfileActionPerformed);

        BtnAlert.setBackground(new java.awt.Color(242, 242, 242));
        BtnAlert.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        BtnAlert.setForeground(new java.awt.Color(255, 255, 255));
        BtnAlert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/alertvolunteer.png"))); // NOI18N
        BtnAlert.setText("Alert");
        BtnAlert.setBorder(null);
        BtnAlert.setContentAreaFilled(false);
        BtnAlert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAlert.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnAlert.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnAlert.addActionListener(this::BtnAlertActionPerformed);

        BtnWork.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        BtnWork.setForeground(new java.awt.Color(255, 255, 255));
        BtnWork.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/disasterrelief.png"))); // NOI18N
        BtnWork.setText("Disaster Relief");
        BtnWork.setBorder(null);
        BtnWork.setContentAreaFilled(false);
        BtnWork.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnWork.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnWork.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnWork.addActionListener(this::BtnWorkActionPerformed);

        BtnLogOut.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        BtnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        BtnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/logout.png"))); // NOI18N
        BtnLogOut.setText("Log Out");
        BtnLogOut.setBorder(null);
        BtnLogOut.setContentAreaFilled(false);
        BtnLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnLogOut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnLogOut.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnWork, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnAlert, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(LogoVolunteer, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LogoVolunteer)
                .addGap(18, 18, 18)
                .addComponent(BtnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnWork, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnLogOut)
                .addContainerGap(415, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnProfileActionPerformed

    private void BtnAlertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAlertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAlertActionPerformed

    private void BtnWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnWorkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnWorkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAlert;
    private javax.swing.JButton BtnLogOut;
    private javax.swing.JButton BtnProfile;
    private javax.swing.JButton BtnWork;
    private javax.swing.JLabel LogoVolunteer;
    // End of variables declaration//GEN-END:variables
}
