/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.dg.spadmindashboard;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author TASNUVA
 */
public class SuperAdminMenuPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminMenu
     */
    public SuperAdminMenuPanel() {
        initComponents();
    }

    public javax.swing.JButton getBtnViewAdmin() {
        return btnViewAdmin;
    }

    public javax.swing.JButton getBtnSearchAdmin() {
        return btnSearchAdmin;
    }

    public javax.swing.JButton getBtnSearchVolunteer() {
        return btnSearchVolunteer;
    }

    public javax.swing.JButton getBtnViewVolunteer() {
        return btnViewVolunteer;
    }

    public javax.swing.JButton getBtnProfile() {
        return btnProfile;
    }

    public javax.swing.JButton getBtnDisasterAlert() {
        return btnDisasterAlert;
    }

    public javax.swing.JButton getBtnAlertStatus() {
        return btnAlertStatus;
    }

    public javax.swing.JButton getBtnLogout() {
        return btnLogout;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnDisasterAlert = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnSearchAdmin = new javax.swing.JButton();
        btnViewAdmin = new javax.swing.JButton();
        btnSearchVolunteer = new javax.swing.JButton();
        btnViewVolunteer = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        btnAlertStatus = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/superadmindashboardlogo.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
        );

        btnDisasterAlert.setBackground(new java.awt.Color(204, 0, 0));
        btnDisasterAlert.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        btnDisasterAlert.setForeground(new java.awt.Color(255, 255, 255));
        btnDisasterAlert.setText(" Generate Alert");
        btnDisasterAlert.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnDisasterAlert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnLogout.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/logout.png"))); // NOI18N
        btnLogout.setText("Log Out");
        btnLogout.setBorder(null);
        btnLogout.setContentAreaFilled(false);
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnLogout.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        btnSearchAdmin.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnSearchAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/searchadmin.png"))); // NOI18N
        btnSearchAdmin.setText("Search Admin");
        btnSearchAdmin.setBorder(null);
        btnSearchAdmin.setContentAreaFilled(false);
        btnSearchAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchAdmin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSearchAdmin.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnSearchAdmin.addActionListener(this::btnSearchAdminActionPerformed);

        btnViewAdmin.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnViewAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnViewAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/viewadmin.png"))); // NOI18N
        btnViewAdmin.setText("View Admin");
        btnViewAdmin.setBorder(null);
        btnViewAdmin.setContentAreaFilled(false);
        btnViewAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewAdmin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnViewAdmin.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnViewAdmin.addActionListener(this::btnViewAdminActionPerformed);

        btnSearchVolunteer.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnSearchVolunteer.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchVolunteer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/viewvolunteericon.png"))); // NOI18N
        btnSearchVolunteer.setText("Search Volunteer");
        btnSearchVolunteer.setBorder(null);
        btnSearchVolunteer.setContentAreaFilled(false);
        btnSearchVolunteer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchVolunteer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSearchVolunteer.addActionListener(this::btnSearchVolunteerActionPerformed);

        btnViewVolunteer.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnViewVolunteer.setForeground(new java.awt.Color(255, 255, 255));
        btnViewVolunteer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/viewvolunteer.png"))); // NOI18N
        btnViewVolunteer.setText("View Volunteer");
        btnViewVolunteer.setBorder(null);
        btnViewVolunteer.setContentAreaFilled(false);
        btnViewVolunteer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewVolunteer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnViewVolunteer.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnViewVolunteer.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnViewVolunteer.addActionListener(this::btnViewVolunteerActionPerformed);

        btnProfile.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/myprofile.png"))); // NOI18N
        btnProfile.setText("My Profile");
        btnProfile.setBorder(null);
        btnProfile.setContentAreaFilled(false);
        btnProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProfile.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnAlertStatus.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnAlertStatus.setForeground(new java.awt.Color(255, 255, 255));
        btnAlertStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/alertstatusicon_1.png"))); // NOI18N
        btnAlertStatus.setText("Alert Status");
        btnAlertStatus.setBorder(null);
        btnAlertStatus.setContentAreaFilled(false);
        btnAlertStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlertStatus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAlertStatus.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAlertStatus.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAlertStatus.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearchAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSearchVolunteer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewVolunteer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlertStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnDisasterAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProfile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearchAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchVolunteer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewVolunteer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlertStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(btnDisasterAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchAdminActionPerformed

    private void btnSearchVolunteerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchVolunteerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchVolunteerActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnViewAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewAdminActionPerformed

    private void btnViewVolunteerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewVolunteerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewVolunteerActionPerformed

    @Override
    protected void paintChildren(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint g = new GradientPaint(0, 0, Color.decode("#004E92"), 0, getHeight(), Color.decode("#000428"));
        g2.setPaint(g);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        g2.fillRect(getWidth() - 20, 0, getWidth(), getHeight());
        super.paintChildren(grphcs);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlertStatus;
    private javax.swing.JButton btnDisasterAlert;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnSearchAdmin;
    private javax.swing.JButton btnSearchVolunteer;
    private javax.swing.JButton btnViewAdmin;
    private javax.swing.JButton btnViewVolunteer;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
