/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.dg.adminform;

import com.dg.dbconnection.AdminData;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author samih
 */
public class AdminQualification extends javax.swing.JPanel {

    /**
     * Creates new form AdminQualification
     */
    public AdminQualification() {
        initComponents();
        setBackground(Color.WHITE);
        setOpaque(false);
    }

    @Override
protected void paintComponent(Graphics g) {
    super.paintComponent(g);

    Graphics2D g2 = (Graphics2D) g.create();
    g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

    int arc = 25;
    int shadow = 8;

    // Shadow
    g2.setColor(new Color(0, 0, 0, 60));
    g2.fillRoundRect(shadow, shadow,
            getWidth() - shadow,
            getHeight() - shadow,
            arc, arc);

    // Background
    g2.setColor(getBackground());
    g2.fillRoundRect(0, 0,
            getWidth() - shadow,
            getHeight() - shadow,
            arc, arc);

    g2.dispose();
}

    
    
    private boolean validateQualificationForm() {

        if (AdminHigherEducationalQualification.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Please select highest educational qualification.");
            return false;
        }

        if (AdminMajorSubject.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter major subject or field.");
            return false;
        }

        if (AdminUniversity.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter university or institution name.");
            return false;
        }

        if (AdminOfficialDesignation.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter official designation.");
            return false;
        }

        if (AdminOrganization.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter organization or department name.");
            return false;
        }

        if (AdminOrganizationType.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Please select organization type.");
            return false;
        }

        if (AdminOfficialIDNumber.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter official ID number.");
            return false;
        }

        if (AdminDateOfJoining.getSelectedIndex() == 0
                || AdminMonthOfJoining.getSelectedIndex() == 0
                || AdminYearOfJoining.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Please select complete joining date.");
            return false;
        }

        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AdminHigherEducationalQualification = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        AdminMajorSubject = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        AdminUniversity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        AdminOfficialDesignation = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        AdminOrganization = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        AdminOrganizationType = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        AdminOfficialIDNumber = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        AdminDateOfJoining = new javax.swing.JComboBox<>();
        AdminMonthOfJoining = new javax.swing.JComboBox<>();
        AdminYearOfJoining = new javax.swing.JComboBox<>();
        AdminQualificationPreviousButton = new javax.swing.JButton();
        AdminQualificationNextButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        jLabel1.setText("Educational Qualification");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setText("Highest Educational Qualification");

        AdminHigherEducationalQualification.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Select One---", "HSC/Equivalent", "Bachelor's Degree", "Master's Degree", "PhD/Doctoral Degree" }));
        AdminHigherEducationalQualification.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));
        AdminHigherEducationalQualification.addActionListener(this::AdminHigherEducationalQualificationActionPerformed);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setText("Major Subject/Field");

        AdminMajorSubject.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel4.setText("University/Institution");

        AdminUniversity.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        jLabel5.setText("Official Designation & Organization");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel6.setText("Official Designation/Position");

        AdminOfficialDesignation.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));
        AdminOfficialDesignation.addActionListener(this::AdminOfficialDesignationActionPerformed);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel7.setText("Organization/Department");

        AdminOrganization.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel8.setText("Organization Type");

        AdminOrganizationType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Select One---", "Government", "Local Government", "NGO (National)", "NGO (International)", "Other" }));
        AdminOrganizationType.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel9.setText("Employee/Official ID Number");

        AdminOfficialIDNumber.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel10.setText("Date of Joining Current Position");

        AdminDateOfJoining.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Select Date---", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        AdminDateOfJoining.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));

        AdminMonthOfJoining.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Select Month---", "January", "February", "March", "April", "May ", "June", "July ", "August", "September", "October", "November", "December", " " }));
        AdminMonthOfJoining.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));

        AdminYearOfJoining.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Select Year---", "2025", "2024", "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971" }));
        AdminYearOfJoining.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));

        AdminQualificationPreviousButton.setBackground(new java.awt.Color(0, 153, 153));
        AdminQualificationPreviousButton.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        AdminQualificationPreviousButton.setForeground(new java.awt.Color(204, 255, 255));
        AdminQualificationPreviousButton.setText("Previous");
        AdminQualificationPreviousButton.addActionListener(this::AdminQualificationPreviousButtonActionPerformed);

        AdminQualificationNextButton.setBackground(new java.awt.Color(0, 153, 153));
        AdminQualificationNextButton.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        AdminQualificationNextButton.setForeground(new java.awt.Color(204, 255, 255));
        AdminQualificationNextButton.setText("Next");
        AdminQualificationNextButton.addActionListener(this::AdminQualificationNextButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AdminHigherEducationalQualification, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AdminMajorSubject)
                                    .addComponent(AdminUniversity, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(AdminOfficialDesignation)
                                        .addComponent(AdminOrganization, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(AdminOfficialIDNumber, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(AdminOrganizationType, javax.swing.GroupLayout.Alignment.LEADING, 0, 138, Short.MAX_VALUE)))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AdminQualificationPreviousButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(AdminDateOfJoining, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(AdminMonthOfJoining, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(AdminYearOfJoining, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                                .addComponent(AdminQualificationNextButton)
                                .addGap(33, 33, 33))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AdminMajorSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(AdminHigherEducationalQualification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(AdminUniversity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel5)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(AdminOfficialDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(AdminOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(AdminOrganizationType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(AdminOfficialIDNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(AdminDateOfJoining, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminMonthOfJoining, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminYearOfJoining, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminQualificationPreviousButton)
                    .addComponent(AdminQualificationNextButton))
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AdminOfficialDesignationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminOfficialDesignationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminOfficialDesignationActionPerformed

    private void AdminQualificationNextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminQualificationNextButtonActionPerformed
        // TODO add your handling code here:
        
        if (!validateQualificationForm()) {
            return;
        }

        MainAdminFrame frame = (MainAdminFrame) SwingUtilities.getWindowAncestor(this);
        AdminData admin=frame.getAdminData();
        admin.setHigherEducation(
            AdminHigherEducationalQualification.getSelectedItem().toString()
    );

    admin.setMajorSubjectField(
            AdminMajorSubject.getText().trim()
    );

    admin.setUniversityInstitution(
            AdminUniversity.getText().trim()
    );

    // ===== Official Designation & Organization =====
    admin.setOfficialDesignation(
            AdminOfficialDesignation.getText().trim()
    );

    admin.setOrganizationDepartment(
            AdminOrganization.getText().trim()
    );

    admin.setOrganizationType(
            AdminOrganizationType.getSelectedItem().toString()
    );

    admin.setEmployeeOfficialIdNumber(
            AdminOfficialIDNumber.getText().trim()
    );

    // ===== Date of Joining =====
    admin.setDateOfJoiningDay(
            Integer.parseInt(AdminDateOfJoining.getSelectedItem().toString())
    );

    admin.setDateOfJoiningMonth(
            AdminMonthOfJoining.getSelectedItem().toString()
    );

    admin.setDateOfJoiningYear(
            Integer.parseInt(AdminYearOfJoining.getSelectedItem().toString())
    );
        frame.showCard("SKILLS");
    }//GEN-LAST:event_AdminQualificationNextButtonActionPerformed

    private void AdminQualificationPreviousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminQualificationPreviousButtonActionPerformed
        // TODO add your handling code here:
        MainAdminFrame frame = (MainAdminFrame) SwingUtilities.getWindowAncestor(this);
        frame.showCard("ADDRESS");

    }//GEN-LAST:event_AdminQualificationPreviousButtonActionPerformed

    private void AdminHigherEducationalQualificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminHigherEducationalQualificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminHigherEducationalQualificationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AdminDateOfJoining;
    private javax.swing.JComboBox<String> AdminHigherEducationalQualification;
    private javax.swing.JTextField AdminMajorSubject;
    private javax.swing.JComboBox<String> AdminMonthOfJoining;
    private javax.swing.JTextField AdminOfficialDesignation;
    private javax.swing.JTextField AdminOfficialIDNumber;
    private javax.swing.JTextField AdminOrganization;
    private javax.swing.JComboBox<String> AdminOrganizationType;
    private javax.swing.JButton AdminQualificationNextButton;
    private javax.swing.JButton AdminQualificationPreviousButton;
    private javax.swing.JTextField AdminUniversity;
    private javax.swing.JComboBox<String> AdminYearOfJoining;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
