/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.dg.adminform;

import java.awt.*;

public class HeaderPanel extends javax.swing.JPanel {

    /**
     * Creates new form HeaderPanel
     */
    public HeaderPanel() {
        initComponents();
        setSize(900, 200);
        setOpaque(false);
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        int radius = 30;
        int shadow = 8;

        // Shadow
        g2.setColor(new Color(0, 0, 0, 50));
        g2.fillRoundRect(shadow, shadow, getWidth() - shadow, getHeight() - shadow, radius, radius);

        // Gradient: Dark → Medium Blue
        GradientPaint gp = new GradientPaint(
                0, 0, new Color(0, 76, 76),
                0, getHeight(), new Color(128, 224, 224)
        );
        g2.setPaint(gp);
        g2.fillRoundRect(0, 0, getWidth() - shadow, getHeight() - shadow, radius, radius);

        g2.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(61, 156, 197));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(189, 231, 218));
        jLabel2.setText("AdminHub");
        add(jLabel2);
        jLabel2.setBounds(350, 0, 210, 50);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(220, 211, 253));
        jLabel1.setText("\"Be the reason someone smiles\"");
        add(jLabel1);
        jLabel1.setBounds(320, 50, 240, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel3.setText("Create Your Own Account");
        add(jLabel3);
        jLabel3.setBounds(270, 80, 330, 33);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
