/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.dg.adminform;

import com.dg.dbconnection.AdminData;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author samih
 */
public class MainAdminFrame extends javax.swing.JFrame {

    private CardLayout cardLayout;
    private AdminData adminData = new AdminData();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainAdminFrame.class.getName());

    /**
     * Creates new form MainAdminFrame
     */
    public MainAdminFrame() {
        initComponents();
        setTitle("Admin Registration Form");
        setMinimumSize(new Dimension(900, 800));
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        if (mainAdminPanel1.getLayout() instanceof CardLayout cardLayout1) {
            cardLayout = cardLayout1;
            cardLayout.show(mainAdminPanel1, "PERSONAL");
        }
        pack();
    }
    public AdminData getAdminData() {
    return adminData;
}

    public void showCard(String cardName) {
        if (cardLayout != null) {
            cardLayout.show(mainAdminPanel1, cardName);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel1 = new com.dg.adminform.HeaderPanel();
        mainAdminPanel1 = new com.dg.adminform.MainAdminPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(headerPanel1, java.awt.BorderLayout.CENTER);
        getContentPane().add(mainAdminPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainAdminFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.dg.adminform.HeaderPanel headerPanel1;
    private com.dg.adminform.MainAdminPanel mainAdminPanel1;
    // End of variables declaration//GEN-END:variables
}
