/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.dg.adminform;

/**
 *
 * @author samih
 */
public class MainAdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainAdminPanel
     */
    public MainAdminPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        personalInfoPanel1 = new com.dg.adminform.PersonalInfoPanel();
        adminQualification1 = new com.dg.adminform.AdminQualification();
        addressPanel1 = new com.dg.adminform.AddressPanel();
        specializedSkillsPanel1 = new com.dg.adminform.SpecializedSkillsPanel();
        physicalCapabilitiesExperiencePanel1 = new com.dg.adminform.AdminExperiencePanel();

        setLayout(new java.awt.CardLayout());
        add(personalInfoPanel1, "PERSONAL");
        add(adminQualification1, "QUALIFICATION");
        add(addressPanel1, "ADDRESS");
        add(specializedSkillsPanel1, "SKILLS");
        add(physicalCapabilitiesExperiencePanel1, "EXPERIENCE");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.dg.adminform.AddressPanel addressPanel1;
    private com.dg.adminform.AdminQualification adminQualification1;
    private com.dg.adminform.PersonalInfoPanel personalInfoPanel1;
    private com.dg.adminform.AdminExperiencePanel physicalCapabilitiesExperiencePanel1;
    private com.dg.adminform.SpecializedSkillsPanel specializedSkillsPanel1;
    // End of variables declaration//GEN-END:variables
}
