/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.dg.adminform;

import com.dg.dbconnection.AdminData;
import com.dg.homepage.Homepage1;
import java.awt.*;
import javax.swing.*;
import java.time.LocalDate;
import java.time.Period;

public class PersonalInfoPanel extends javax.swing.JPanel {

    /**
     * Creates new form PersonalInfoPanel
     */
    private ButtonGroup genderGroup;

    public PersonalInfoPanel() {
        initComponents();
        setBackground(Color.WHITE);
        setOpaque(false);

        genderGroup = new ButtonGroup();
        genderGroup.add(AdminGenderMale);
        genderGroup.add(AdminGenderFemale);
        genderGroup.add(AdminGenderOther);

    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        Graphics2D g2 = (Graphics2D) g.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        int arc = 25;
        int shadow = 8;

        // Shadow
        g2.setColor(new Color(0, 0, 0, 60));
        g2.fillRoundRect(shadow, shadow,
                getWidth() - shadow,
                getHeight() - shadow,
                arc, arc);

        // Background
        g2.setColor(getBackground());
        g2.fillRoundRect(0, 0,
                getWidth() - shadow,
                getHeight() - shadow,
                arc, arc);

        g2.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel = new javax.swing.JLabel();
        AdminName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        AdminBirthDate = new javax.swing.JComboBox<>();
        AdminBirthMonth = new javax.swing.JComboBox<>();
        AdminBirthYear = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        AdminGenderMale = new javax.swing.JRadioButton();
        AdminGenderFemale = new javax.swing.JRadioButton();
        AdminGenderOther = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        AdminNationalID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        AdminPhoneNumber = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        AdminEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        AdminBloodGroup = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        AdminEmergencyContactNo = new javax.swing.JTextField();
        PersonalInfoNextButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        PersonalInfoBackButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        AdminAlternativePhoneNumber = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        AdminEmergencyContactName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        AdminEmergencyContactRelationship = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLabel.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel.setText("Name");

        AdminName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setText("Birth Date");

        AdminBirthDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Select Date---", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        AdminBirthDate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));
        AdminBirthDate.addActionListener(this::AdminBirthDateActionPerformed);

        AdminBirthMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Select Month---", "January", "February", "March", "April", "May ", "June", "July ", "August", "September", "October", "November", "December" }));
        AdminBirthMonth.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));
        AdminBirthMonth.addActionListener(this::AdminBirthMonthActionPerformed);

        AdminBirthYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Select Year---", "2025", "2024", "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971" }));
        AdminBirthYear.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));
        AdminBirthYear.addActionListener(this::AdminBirthYearActionPerformed);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setText("Gender");

        AdminGenderMale.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AdminGenderMale.setText("Male");

        AdminGenderFemale.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AdminGenderFemale.setText("Female");
        AdminGenderFemale.addActionListener(this::AdminGenderFemaleActionPerformed);

        AdminGenderOther.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AdminGenderOther.setText("Other");
        AdminGenderOther.addActionListener(this::AdminGenderOtherActionPerformed);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setText("National ID");

        AdminNationalID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));
        AdminNationalID.addActionListener(this::AdminNationalIDActionPerformed);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        jLabel4.setText("Contact Details");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel5.setText("Phone Number");

        AdminPhoneNumber.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));
        AdminPhoneNumber.addActionListener(this::AdminPhoneNumberActionPerformed);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel6.setText("Email");

        AdminEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));
        AdminEmail.addActionListener(this::AdminEmailActionPerformed);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel7.setText("Blood Group");

        AdminBloodGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Select Blood Group---", "A+", "A-", "AB+", "AB-", "B+", "B-", "O+", "O-" }));
        AdminBloodGroup.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));
        AdminBloodGroup.addActionListener(this::AdminBloodGroupActionPerformed);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel8.setText("Emergency Contact Number");

        AdminEmergencyContactNo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));

        PersonalInfoNextButton1.setBackground(new java.awt.Color(0, 153, 153));
        PersonalInfoNextButton1.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        PersonalInfoNextButton1.setForeground(new java.awt.Color(204, 255, 255));
        PersonalInfoNextButton1.setText("Next");
        PersonalInfoNextButton1.setAutoscrolls(true);
        PersonalInfoNextButton1.addActionListener(this::PersonalInfoNextButton1ActionPerformed);

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Personal Details");

        PersonalInfoBackButton.setBackground(new java.awt.Color(0, 153, 153));
        PersonalInfoBackButton.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        PersonalInfoBackButton.setForeground(new java.awt.Color(204, 255, 255));
        PersonalInfoBackButton.setText("Back");
        PersonalInfoBackButton.addActionListener(this::PersonalInfoBackButtonActionPerformed);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel10.setText("Alternative Phone Number");

        AdminAlternativePhoneNumber.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel11.setText("Emergency Contact Name");

        AdminEmergencyContactName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel12.setText("Emergency Contact Relationship");

        AdminEmergencyContactRelationship.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Select One---", "Spouse", "Parent", "Sibling", "Child", "Friend", "Colleague", "Other" }));
        AdminEmergencyContactRelationship.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));
        AdminEmergencyContactRelationship.addActionListener(this::AdminEmergencyContactRelationshipActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(PersonalInfoBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PersonalInfoNextButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AdminEmergencyContactRelationship, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(AdminEmergencyContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel7))
                                        .addGap(71, 71, 71)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(AdminBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(AdminBirthMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(48, 48, 48)
                                                .addComponent(AdminBirthYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(AdminGenderMale)
                                                        .addGap(46, 46, 46)
                                                        .addComponent(AdminGenderFemale)
                                                        .addGap(45, 45, 45)
                                                        .addComponent(AdminGenderOther))
                                                    .addComponent(AdminName, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(AdminNationalID, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(AdminBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11))
                                        .addGap(47, 47, 47)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AdminEmergencyContactName, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(AdminAlternativePhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(AdminEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(AdminPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 19, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel)
                    .addComponent(AdminName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(AdminBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminBirthMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminBirthYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(AdminGenderMale)
                    .addComponent(AdminGenderFemale)
                    .addComponent(AdminGenderOther))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(AdminNationalID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(AdminBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(AdminPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(AdminEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminAlternativePhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(AdminEmergencyContactName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(AdminEmergencyContactRelationship, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(AdminEmergencyContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PersonalInfoNextButton1)
                    .addComponent(PersonalInfoBackButton))
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AdminBirthDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminBirthDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminBirthDateActionPerformed

    private void AdminBloodGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminBloodGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminBloodGroupActionPerformed

    private void AdminNationalIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminNationalIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminNationalIDActionPerformed

    private void PersonalInfoNextButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonalInfoNextButton1ActionPerformed

        // Name validation
        
        String adminName = AdminName.getText().trim();

        if (adminName.isEmpty() || !adminName.matches("[A-Za-z ]{3,50}")) {
            JOptionPane.showMessageDialog(this,
                    "Name must contain only letters and minimum 3 characters!");
            AdminName.requestFocusInWindow();
            return;
        }

// Check selection
        if (AdminBirthDate.getSelectedIndex() == 0
                || AdminBirthMonth.getSelectedIndex() == 0
                || AdminBirthYear.getSelectedIndex() == 0) {

            JOptionPane.showMessageDialog(this, "Please select complete birth date!");
            AdminBirthDate.requestFocusInWindow();
            return;
        }

        try {
            int day = Integer.parseInt(AdminBirthDate.getSelectedItem().toString());
            int year = Integer.parseInt(AdminBirthYear.getSelectedItem().toString());

            String monthStr = AdminBirthMonth.getSelectedItem().toString();
            int month;

            switch (monthStr) {
                case "January" ->
                    month = 1;
                case "February" ->
                    month = 2;
                case "March" ->
                    month = 3;
                case "April" ->
                    month = 4;
                case "May" ->
                    month = 5;
                case "June" ->
                    month = 6;
                case "July" ->
                    month = 7;
                case "August" ->
                    month = 8;
                case "September" ->
                    month = 9;
                case "October" ->
                    month = 10;
                case "November" ->
                    month = 11;
                case "December" ->
                    month = 12;
                default ->
                    throw new Exception();
            }

            // Month-wise day validation 
            boolean leapYear
                    = (year % 4 == 0 && year % 100 != 0) || (year % 400 == 0);

            if (month == 2) { // February
                if (leapYear && day > 29) {
                    JOptionPane.showMessageDialog(this,
                            "February in leap year has maximum 29 days!");
                    AdminBirthDate.requestFocusInWindow();
                    return;
                }
                if (!leapYear && day > 28) {
                    JOptionPane.showMessageDialog(this,
                            "February has maximum 28 days!");
                    AdminBirthDate.requestFocusInWindow();
                    return;
                }
            }

            // Months with 30 days
            if ((month == 4 || month == 6 || month == 9 || month == 11) && day > 30) {
                JOptionPane.showMessageDialog(this,
                        "Selected month has maximum 30 days!");
                AdminBirthDate.requestFocusInWindow();
                return;
            }

            // Proper date creation 
            LocalDate birthDate = LocalDate.of(year, month, day);
            LocalDate today = LocalDate.now();

            // Future date check
            if (birthDate.isAfter(today)) {
                JOptionPane.showMessageDialog(this,
                        "Birth date cannot be in future!");
                AdminBirthDate.requestFocusInWindow();
                return;
            }

            // Age calculation
            int age = Period.between(birthDate, today).getYears();

            if (age < 18) {
                JOptionPane.showMessageDialog(this,
                        "Minimum age must be 18 years!\nYour age: " + age);
                AdminBirthDate.requestFocusInWindow();
                return;
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Invalid birth date!");
            AdminBirthDate.requestFocusInWindow();
            return;
        }

// Gender Validation
        if (!AdminGenderMale.isSelected()
                && !AdminGenderFemale.isSelected()
                && !AdminGenderOther.isSelected()) {
            JOptionPane.showMessageDialog(this, "Please select your gender!");
            return;
        }

// National ID Full Validation
        {
            String nid = AdminNationalID.getText().trim();

            try {
                // Reset border first (success case)
                AdminNationalID.setBorder(
                        UIManager.getBorder("TextField.border")
                );

                // Empty check
                if (nid.isEmpty()) {
                    throw new Exception("National ID is required!");
                }

                // Numeric only check
                if (!nid.matches("\\d+")) {
                    throw new Exception("National ID must contain digits only!");
                }

                // Length validation (Bangladesh NID)
                if (!(nid.length() == 10 || nid.length() == 13 || nid.length() == 17)) {
                    throw new Exception("Valid National ID required!");
                }

                // Age check (NID holder must be 18+)
                LocalDate today = LocalDate.now();
                int day = Integer.parseInt(AdminBirthDate.getSelectedItem().toString());
                int year = Integer.parseInt(AdminBirthYear.getSelectedItem().toString());

                String monthStr = AdminBirthMonth.getSelectedItem().toString();
                int month;

                month = switch (monthStr) {
                    case "January" ->
                        1;
                    case "February" ->
                        2;
                    case "March" ->
                        3;
                    case "April" ->
                        4;
                    case "May" ->
                        5;
                    case "June" ->
                        6;
                    case "July" ->
                        7;
                    case "August" ->
                        8;
                    case "September" ->
                        9;
                    case "October" ->
                        10;
                    case "November" ->
                        11;
                    case "December" ->
                        12;
                    default ->
                        1;
                };
                LocalDate birthDate = LocalDate.of(year, month, day);

                int age = Period.between(birthDate, today).getYears();

                if (age < 18) {
                    throw new Exception(
                            "National ID is only valid for age 18+\nYour age: " + age
                    );
                }

            } catch (Exception e) {
                // Show message
                JOptionPane.showMessageDialog(this, e.getMessage());

                // Red border on error
                AdminNationalID.setBorder(
                        BorderFactory.createLineBorder(Color.RED, 2)
                );

                // Grab focus
                AdminNationalID.requestFocusInWindow();
                return;
            }
        }
        // End National ID Validation

        //Blood Group Validation
        if (AdminBloodGroup.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Please select blood group!");
            return;
        }

//Phone Number Validation
        String phone = AdminPhoneNumber.getText().trim();

        if (!phone.matches("01[3-9]\\d{8}")) {
            JOptionPane.showMessageDialog(this,
                    "Invalid phone number!\nExample: 017XXXXXXXX");
            AdminPhoneNumber.requestFocusInWindow();
            return;
        }

        //Email Validation
        String email = AdminEmail.getText().trim();
        if (!email.matches("^[\\w.-]+@[\\w.-]+\\.[A-Za-z]{2,}$")) {
            JOptionPane.showMessageDialog(this, "Enter a valid email address!");
            AdminEmail.requestFocusInWindow();
            return;
        }

        //Alternative Phone Number
        String altPhone = AdminAlternativePhoneNumber.getText().trim();
        if (!altPhone.isEmpty() && !altPhone.matches("01[3-9]\\d{8}")) {
            JOptionPane.showMessageDialog(this, "Invalid alternative phone number!");
            AdminAlternativePhoneNumber.requestFocusInWindow();
            return;
        }

        //Emergency Contact Name
        String ecName = AdminEmergencyContactName.getText().trim();

        if (ecName.isEmpty() || !ecName.matches("[A-Za-z ]+")) {
            JOptionPane.showMessageDialog(this,
                    "Emergency contact name required (letters only)!");
            AdminEmergencyContactName.requestFocusInWindow();
            return;
        }

        //Emergency Contact Relationship
        if (AdminEmergencyContactRelationship.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this,
                    "Please select emergency contact relationship!");
            return;
        }

// Emergency Phone Number validation
        String ephone = AdminEmergencyContactNo.getText().trim();
        if (!ephone.matches("01[3-9]\\d{8}")) {
            JOptionPane.showMessageDialog(this,
                    "Invalid emergency contact number!");
            AdminEmergencyContactNo.requestFocusInWindow();
            return;
        }
        if (!AdminAlternativePhoneNumber.getText().trim().isEmpty()
                && AdminAlternativePhoneNumber.getText().equals(AdminPhoneNumber.getText())) {

            JOptionPane.showMessageDialog(this,
                    "Alternative phone must be different from primary phone!");
            AdminAlternativePhoneNumber.requestFocusInWindow();
            return;
        }


        // If everything is OK
        MainAdminFrame frame = (MainAdminFrame) SwingUtilities.getWindowAncestor(this);
        AdminData admin=frame.getAdminData();
        admin.setFullName(AdminName.getText().trim());

// Birth Date
admin.setBirthDate(
        Integer.parseInt(AdminBirthDate.getSelectedItem().toString())
);
admin.setBirthMonth(
        AdminBirthMonth.getSelectedItem().toString()
);
admin.setBirthYear(
        Integer.parseInt(AdminBirthYear.getSelectedItem().toString())
);

// Gender
if (AdminGenderMale.isSelected()) {
    admin.setGender("Male");
} else if (AdminGenderFemale.isSelected()) {
    admin.setGender("Female");
} else {
    admin.setGender("Other");
}

// National ID
admin.setNid(AdminNationalID.getText().trim());

/* ===============================
   CONTACT INFORMATION
   =============================== */

// Phone & Email
admin.setPhoneNumber(AdminPhoneNumber.getText().trim());
admin.setEmail(AdminEmail.getText().trim());

// Blood Group
admin.setBloodGroup(AdminBloodGroup.getSelectedItem().toString());

// Emergency Contact Number
admin.setEmergencyContactNumber(
        AdminEmergencyContactNo.getText().trim()
);

// Alternative Phone (optional)
admin.setAlternativePhoneNumber(
        AdminAlternativePhoneNumber.getText().trim().isEmpty()
                ? null
                : AdminAlternativePhoneNumber.getText().trim()
);

// Emergency Contact Name
admin.setEmergencyContactName(
        AdminEmergencyContactName.getText().trim()
);

// Emergency Contact Relationship
admin.setEmergencyContactRelationship(
        AdminEmergencyContactRelationship.getSelectedItem().toString()
);
        frame.showCard("ADDRESS");
    }//GEN-LAST:event_PersonalInfoNextButton1ActionPerformed

    private void AdminBirthYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminBirthYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminBirthYearActionPerformed

    private void AdminGenderFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminGenderFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminGenderFemaleActionPerformed

    private void AdminGenderOtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminGenderOtherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminGenderOtherActionPerformed

    private void AdminBirthMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminBirthMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminBirthMonthActionPerformed

    private void AdminPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminPhoneNumberActionPerformed

    private void AdminEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminEmailActionPerformed

    private void PersonalInfoBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonalInfoBackButtonActionPerformed
        // TODO add your handling code here:
        JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);

        // Homepage frame
        Homepage1 homepage = new Homepage1();
        homepage.setVisible(true);

        // Current frame close
        currentFrame.dispose();
    }//GEN-LAST:event_PersonalInfoBackButtonActionPerformed

    private void AdminEmergencyContactRelationshipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminEmergencyContactRelationshipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminEmergencyContactRelationshipActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdminAlternativePhoneNumber;
    private javax.swing.JComboBox<String> AdminBirthDate;
    private javax.swing.JComboBox<String> AdminBirthMonth;
    private javax.swing.JComboBox<String> AdminBirthYear;
    private javax.swing.JComboBox<String> AdminBloodGroup;
    private javax.swing.JTextField AdminEmail;
    private javax.swing.JTextField AdminEmergencyContactName;
    private javax.swing.JTextField AdminEmergencyContactNo;
    private javax.swing.JComboBox<String> AdminEmergencyContactRelationship;
    private javax.swing.JRadioButton AdminGenderFemale;
    private javax.swing.JRadioButton AdminGenderMale;
    private javax.swing.JRadioButton AdminGenderOther;
    private javax.swing.JTextField AdminName;
    private javax.swing.JTextField AdminNationalID;
    private javax.swing.JTextField AdminPhoneNumber;
    private javax.swing.JButton PersonalInfoBackButton;
    private javax.swing.JButton PersonalInfoNextButton1;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
